application: tlatokenizer
version: 1
runtime: python
api_version: 1

handlers:
- url: /style
  static_dir: style

- url: /js
  static_dir: js

- url: /img
  static_dir: img

- url: /plaintext_tokenize
  script: plaintext_tokenize.py

- url: /return_texts
  script: find_texts.py

- url: /.*
  script: index.py
